version: "3.4"

services:
  pricemap-python:
    image: ghcr.io/meilleursagents/backend-technical-test/pricemap-python:latest
    user: "pricemap:pricemap"
    volumes:
      - ./pricemap-python:/home/pricemap/app:rw
    command:
      [
        "/home/pricemap/wait-for-postgres.sh",
        "db:5432",
        "--",
        "python",
        "app.py"
      ]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGDATABASE: pricemap
      PGUSER: pricemap
      PGPASSWORD: pricemap

  typescript-serverless:
    build: typescript-serverless
    user: "$USER_ID:$GROUP_ID"
    volumes:
      - ./typescript-serverless:/home/listingsapi/app:rw
      - /home/listingsapi/app/node_modules
      - ./schemas:/home/listingsapi/schemas:rw
    command: ["npm", "run", "watch"]
    ports:
      - "8383:3000"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGDATABASE: pricemap
      PGUSER: pricemap
      PGPASSWORD: pricemap

  pricemap-dotnet:
    image: ${DOCKER_REGISTRY-}pricemap
    build:
      context: .
      dockerfile: pricemap-dotnet/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8686:443"
      - "60408:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./pricemap-dotnet:/home/pricemap/src:rw
      - ./pricemap-dotnet:/home/pricemap/app:rw

  db:
    image: "mdillon/postgis:11-alpine"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - ./pricemap-python/docker/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "pricemap"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_DB: pricemap
      POSTGRES_USER: pricemap
      POSTGRES_PASSWORD: pricemap

volumes:
  pg-data:
