version: "3.4"

services:
  listingapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8686:80
    depends_on:
      - db
  db:
    image: "mdillon/postgis:11-alpine"
    volumes:
      - ./Db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "listingapi", "-d", "listingapi"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_DB: listingapi
      POSTGRES_USER: listingapi
      POSTGRES_PASSWORD: listingapi

volumes:
  pg-data:
