version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  api:
    build:
      context: ../
    command:
      [
        "/home/listingapi/wait-for-postgres.sh",
        "db:5432",
        "--",
        "python",
        "app.py"
      ]
    depends_on:
      - db
    environment:
      PGHOST: db
      PGDATABASE: listing
      PGUSER: listing
      PGPASSWORD: listing

  db:
    image: "mdillon/postgis:11-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: listing
      POSTGRES_USER: listing
      POSTGRES_PASSWORD: listing

volumes:
  postgres-data:
