openapi: 3.1.0
info:
  title: Pricemap
  version: '1.0'
servers:
  - url: /api
    description: ''
paths:
  /geoms:
    get:
      summary: Get geoms
      description: Get the geoms for the map
      tags: []
      operationId: get-geoms
      responses:
        '200':
          $ref: '#/components/responses/FeatureCollection'
  '/get_price/{cog}':
    parameters:
      - schema:
          type: string
        name: cog
        in: path
        required: true
        description: The cog to get the price for
    get:
      summary: Get price cog
      description: Get the price of a cog
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Serie'
      operationId: get-price-cog
components:
  schemas: {}
  responses:
    FeatureCollection:
      description: A feature collection
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              type:
                type: string
                enum:
                  - FeatureCollection
              features:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - Feature
                    geometry:
                      type: object
                    properties:
                      type: object
                      properties:
                        cog:
                          type: string
                        price:
                          type: string
    Serie:
      description: A serie
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              serie_name:
                type: string
              volumes:
                type: array
                items:
                  type: integer
              labels:
                type: array
                items:
                  type: string

