name: TypeScript React

on:
  push:
    paths:
    - typescript-react/**
    - .github/workflows/ci-typescript-react.yaml

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: "./typescript-react"
          push: false
          target: builder

      - name: Test
        uses: docker/build-push-action@v3
        with:
          context: "./typescript-react"
          push: false
          target: tester
