name: "Lint OpenAPI specifications"

on: [push]

jobs:
  lint_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: stoplightio/spectral-action@0.8.8
        with:
          file_glob: "./schemas/*.yaml"
          spectral_ruleset:
            extends: ["spectral:oas"]
