name: "Lint OpenAPI specifications"

on: [push]

jobs:
  lint_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: stoplightio/spectral-action@latest
        working-directory: ./schemas
        with:
          file_glob: "schemas/*.yaml"
