on: [push]

jobs:
  lint_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'schemas/*.yaml'

